language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y time

install:
  - bundle install

script: 
  - bundle exec tf make-csv_comment_test.sh --text
